name: Build and Deploy
on:
  push:	
    branches:	
      - dev-vp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install 
    - run: git clone https://github.com/roy-lau/blog.git -b src --depth=1 src
    - run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./docs-dist # 发布目录
        publish_branch: gh-pages # 发布分支