name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: grasilife/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: dev-vp # 原分支
        BRANCH: gh-pages # 目标分支
        FOLDER: docs-dist # 原分支的静态文件路径
        BUILD_SCRIPT: npm install && npm run-script getsrc && npm run-script build # deploy 脚本
